### PR TITLE
feat: bump minor version 0.20.1

### PR DESCRIPTION
**Pull request by lgrossi**

### CODE REVIEW

**Comment by lgrossi** [comment]
Hi @NiklasEi, I've pushed the needed changes to release a new minor version.
Would it also be possible to release the 0.20.1 in cargo?

Thanks a ton!

**Review by NiklasEi — APPROVED** [review]
Thanks, I'll try to get it published asap

**Comment by NiklasEi** [comment]
Version 0.20.1 is published. You do not need to register the new dynamic asset collection type anymore, the plugin now does it for you. The same goes for adding a ron asset plugin for the file ending.

**Comment by lgrossi** [comment]
Amazing, thank you very much!

**Pull request merged**
